CREATE DATABASE unicommerce

CREATE TABLE `categoria` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `STATUS` tinyint NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `unicommerce`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(120) NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(150) NULL,
  `bairro` VARCHAR(150) NULL,
  `cidade` VARCHAR(150) NULL,
  `estado` CHAR(2) NULL,
  PRIMARY KEY (`id`));


CREATE TABLE `cliente` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `CPF` varchar(14) NOT NULL,
  `TELEFONE` varchar(14) DEFAULT NULL,
  `ENDERECO_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ENDERECO_ID` FOREIGN KEY (`ENDERECO_ID`) REFERENCES `endereco` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `pedido` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DATA` datetime NOT NULL,
  `CLIENTE_ID` int DEFAULT NULL,
  `DESCONTO` float NOT NULL,
  `TIPO_DESCONTO` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CLIENTE_ID` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `cliente` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `produto` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `PRECO` decimal,
  `QUANTIDADE_ESTOQUE` int DEFAULT NULL,
  `CATEGORIA_ID` int NOT NULL,
  PRIMARY KEY (`ID`,`CATEGORIA_ID`),
  CONSTRAINT `CATEGORIA_ID` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `categoria` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `item_pedido` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PRECO_UNITARIO` decimal(10,0) NOT NULL,
  `QUANTIDADE` int NOT NULL,
  `PEDIDO_ID` int NOT NULL,
  `PRODUTO_ID` int DEFAULT NULL,
  `DESCONTO` decimal(10,0) DEFAULT NULL,
  `TIPO_DESCONTO` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PEDIDO_ID` FOREIGN KEY (`PEDIDO_ID`) REFERENCES `pedido` (`ID`),
  CONSTRAINT `PRODUTO_ID` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `produto` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci