create database unicommerce;
USE unicommerce;



CREATE TABLE CATEGORIA (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  STATUS_ID INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO TEXT,
  QUANTIDADE_ESTOQUE INT NOT NULL,
  CATEGORIA_ID INT NOT NULL,
  Preco decimal not null ,
  PRIMARY KEY (ID),
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(30) NOT NULL,
    senha VARCHAR(250) NOT NULL,
    UNIQUE (login)
);


CREATE TABLE CLIENTE (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  TELEFONE VARCHAR(20) NOT NULL,
  RUA VARCHAR(100),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(100),
  BAIRRO VARCHAR(100),
  CIDADE VARCHAR(100),
  ESTADO VARCHAR(50),
  User_id int NOT NULL,
	FOREIGN KEY (user_id) REFERENCES User(id),
  PRIMARY KEY (ID)
);


CREATE TABLE PEDIDO (
  ID INT NOT NULL AUTO_INCREMENT,
  DATA DATE NOT NULL,
  CLIENTE_ID INT NOT NULL,
  DESCONTO_ID INT NOT NULL,
  TIPO_DESCONTO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE ITEM_PEDIDO (
  ID INT NOT NULL AUTO_INCREMENT,
  PRECO_UNITARIO DECIMAL(19, 2) NOT NULL,
  QUANTIDADE INT NOT NULL,
  PEDIDO_ID INT NOT NULL,
  PRODUTO_ID INT NOT NULL,
  DESCONTO_ID INT NOT NULL,
  TIPO_DESCONTO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
  FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);
